<?php

namespace FormArmorBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByClientAndSession($pClient, $pSession) // Controle du nom et du mot de passe
	{
		$qb = $this->createQueryBuilder('c');
		$qb->select('COUNT(c)');
		$qb->andWhere('c.client = :pClient AND c.sessionFormation = :pSession')->setParameter('pClient', $pClient)->setParameter('pSession',   $pSession);
		return $qb->getQuery()->getSingleScalarResult();
	}
	public function listeHistorique($page, $nbParPage,$pClient) // Liste toutes les sessions avec pagination
	{
		$qb = $this->createQueryBuilder('c');
		$qb->andWhere('c.client = :pClient')->setParameter('pClient', $pClient);
		$query = $qb->getQuery();
		$query->setFirstResult(($page-1) * $nbParPage)->setMaxResults($nbParPage);
		return new Paginator($query, true);
	}
}
