<?php

namespace FormArmorBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SessionsAutoriseesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sessions_AutoriseesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBySession($pIdSession) // Controle du nom et du mot de passe
	{
		$qb = $this->createQueryBuilder('c');
		$qb->andWhere('c.session = :pIdSession')->setParameter('pIdSession',   $pIdSession);
		return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
	}
    public function listeSessionsClient($pIdClient) // Liste toutes les sessions avec pagination
	{       
		$this->getEntityManager()->getConnection()->query("call SessionsAutorisees($pIdClient)");

        $queryBuilder = $this->createQueryBuilder('s');  
		$query = $queryBuilder->getQuery();
		return $query->getResult();
	}
}
