<?php

namespace FormArmorBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Session_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Session_formationRepository extends \Doctrine\ORM\EntityRepository
{
	public function listeSessions($page, $nbParPage) // Liste toutes les sessions avec pagination
	{
		$date = new \DateTime("NOW");
		$queryBuilder = $this->createQueryBuilder('s');
		$queryBuilder->where('s.dateDebut > :dateDuJour')->setParameter('dateDuJour', $date)->orderBy('s.dateDebut', 'asc');
		$query = $queryBuilder->getQuery();
		$query->setFirstResult(($page-1) * $nbParPage)->setMaxResults($nbParPage);
		return new Paginator($query, true);
	}
	public function listeSessionsClient($page, $nbParPage) // Liste toutes les sessions disponibles au cours des 2 mois
	{
		$date = new \DateTime("NOW");
		$dateMois = (new \DateTime("NOW"))->add(new \DateInterval('P2M'));
		$queryBuilder = $this->createQueryBuilder('s');
		$queryBuilder->where('s.dateDebut BETWEEN :date AND :date2')
		->setParameter('date',$date->format('Y-m-d'))
		->setParameter('date2',$dateMois->format('Y-m-d'))
		->orderBy('s.dateDebut', 'asc');
		$query = $queryBuilder->getQuery();
		$query->setFirstResult(($page-1) * $nbParPage)->setMaxResults($nbParPage);
		return new Paginator($query, true);
	}
	public function suppSession($id) // Suppression de la session d'identifiant $id
	{
		$qb = $this->createQueryBuilder('s');
		$query = $qb->delete('FormArmorBundle\Entity\Session_formation', 's')
		  ->where('s.id = :id')
		  ->setParameter('id', $id);
		
		return $qb->getQuery()->getResult();
	}
}
